# Generated by Django 2.2 on 2019-04-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField()),
                ('content', models.TextField(max_length=100000)),
            ],
        ),
    ]
